### ISSUE TITLE
var opts = pc.platform.passiveEvents ? { passive: false } : false;

### ISSUE THREAD

**Issue by kungfooman** [yaustar/yaustar.github.io#21]
https://github.com/yaustar/yaustar.github.io/blob/master/playcanvas-devtools/debug-gamepad-flycamera.js#L42

Does this code do anything or did it in the past? As far I can see this is never handled by the engine:

![image](https://user-images.githubusercontent.com/5236548/127838795-c5ff08b0-a1eb-4c1d-9a81-cdfbdc0c2a21.png)

`pc.Mouse#constructor` has no arguments and `pc.Keyboard#constructor` looks for `preventDefault` and `stopPropagation` only

**Comment by yaustar** [comment]
Ah, this was leftover code from when I was listening to events directly from the window 😅

**Comment by yaustar** [comment]
Fixed in https://github.com/yaustar/yaustar.github.io/commit/c0245874935bbbc792226efe6d6f5b097fca0c95#diff-970610ce52592132372b2a7aad641f3f692bbf47211b1f9fadfa0521124a4100
